// <auto-generated />
using System;
using Majlis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Majlis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MajlisDbContext))]
    [Migration("20260828124324_RecordDailyMajlisPublicationHistory")]
    partial class RecordDailyMajlisPublicationHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "RevisionId")
                        .HasName("AK_Challenges_Id_RevisionId");

                    b.HasIndex("RevisionId")
                        .IsUnique();

                    b.ToTable("Challenges", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.ChallengeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ChallengeId")
                        .HasName("AK_ChallengeOptions_Id_ChallengeId");

                    b.HasIndex("ChallengeId", "OptionKey")
                        .IsUnique();

                    b.HasIndex("ChallengeId", "SortOrder")
                        .IsUnique();

                    b.ToTable("ChallengeOptions", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.ChallengeOptionTranslation", b =>
                {
                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OptionId", "Locale");

                    b.ToTable("ChallengeOptionTranslations", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("PublishedRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduledRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PublishDate")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('scheduled', 'published')");

                    b.HasIndex("PublishedRevisionId");

                    b.HasIndex("ScheduledRevisionId");

                    b.ToTable("DailyMajlis", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlisPublication", b =>
                {
                    b.Property<Guid>("DailyMajlisId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DailyMajlisId");

                    b.HasIndex("PublishDate")
                        .IsUnique();

                    b.ToTable("DailyMajlisPublications", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlisRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyMajlisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SourceNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersedesRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SupersedesRevisionId");

                    b.HasIndex("DailyMajlisId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("DailyMajlisRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyMajlisRevisions_SourceNotes", "length(btrim(\"SourceNotes\")) > 0");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlisTranslation", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("CardContext")
                        .HasColumnType("text");

                    b.Property<string>("CardMeaning")
                        .HasColumnType("text");

                    b.Property<string>("CardText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardTitle")
                        .HasColumnType("text");

                    b.Property<string>("CorrectionNote")
                        .HasColumnType("text");

                    b.Property<string>("DiscussionPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicAttribution")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transliteration")
                        .HasColumnType("text");

                    b.HasKey("RevisionId", "Locale");

                    b.ToTable("DailyMajlisTranslations", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.RevisionDialect", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DialectCode")
                        .HasColumnType("text");

                    b.HasKey("RevisionId", "DialectCode");

                    b.ToTable("RevisionDialects", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.RevisionRegion", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegionCode")
                        .HasColumnType("text");

                    b.HasKey("RevisionId", "RegionCode");

                    b.ToTable("RevisionRegions", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.Identity.AccountDeletionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BackupExpiryDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalHoldReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PurgeDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'completed'");

                    b.ToTable("AccountDeletionRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountDeletionRequests_Status", "\"Status\" IN ('requested', 'identity_deleted', 'active_data_purged', 'backup_expiry_pending', 'completed', 'legal_hold')");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AuthenticationNotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Status", "\"Status\" IN ('active', 'suspended', 'deletion_pending', 'deleted')");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Type", "Version")
                        .IsUnique();

                    b.ToTable("UserConsents", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserConsents_Type", "\"Type\" IN ('terms', 'privacy', 'analytics')");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastAuthenticatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProviderAuthorizationRevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RevocationHandleCiphertext")
                        .HasColumnType("bytea");

                    b.Property<string>("RevocationKeyVersion")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("UserIdentities", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserIdentities_Provider", "\"Provider\" IN ('google', 'apple', 'meta', 'snapchat', 'test')");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AnalyticsConsent")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("ReminderLocalTime")
                        .HasColumnType("time");

                    b.Property<string>("ReminderTimeZoneId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgeBand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AgeBandAttestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DialectCode")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayNameNormalized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeaderboardVisibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Profiles_AgeBand", "\"AgeBand\" IN ('13_17', '18_plus')");

                            t.HasCheckConstraint("CK_Profiles_CountryCode", "\"CountryCode\" IS NULL OR \"CountryCode\" ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("CK_Profiles_DisplayNameStorageLength", "char_length(btrim(\"DisplayName\")) BETWEEN 1 AND 120");

                            t.HasCheckConstraint("CK_Profiles_LeaderboardVisibility", "\"LeaderboardVisibility\" IN ('private', 'global_weekly')");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("UserId", "Role")
                        .IsUnique()
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.ToTable("UserRoleAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserRoleAssignments_Role", "\"Role\" IN ('moderator', 'content_editor', 'content_reviewer', 'publisher', 'operations_admin')");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.Progress.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Scope", "IdempotencyKey")
                        .HasName("PK_IdempotencyRecords");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_IdempotencyRecords_ExpiresAt");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("Majlis.Domain.Progress.UserAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionXp")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectnessXp")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreakAfter")
                        .HasColumnType("integer");

                    b.Property<Guid>("DailyMajlisId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<long>("LifetimeXpAfter")
                        .HasColumnType("bigint");

                    b.Property<int>("LongestStreakAfter")
                        .HasColumnType("integer");

                    b.Property<string>("ResultLocale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DailyMajlisId");

                    b.HasIndex("ChallengeId", "ContentRevisionId");

                    b.HasIndex("SelectedOptionId", "ChallengeId");

                    b.HasIndex("UserId", "DailyMajlisId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserAttempts_UserId_DailyMajlisId");

                    b.HasIndex("UserId", "AttemptedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_UserAttempts_UserId_AttemptedAt_Id");

                    b.ToTable("UserAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserAttempts_ExactXpAndSnapshots", "\"CompletionXp\" = 10 AND \"CorrectnessXp\" IN (0, 5) AND ((\"IsCorrect\" AND \"CorrectnessXp\" = 5) OR (NOT \"IsCorrect\" AND \"CorrectnessXp\" = 0)) AND \"LifetimeXpAfter\" >= 0 AND \"CurrentStreakAfter\" >= 0 AND \"LongestStreakAfter\" >= \"CurrentStreakAfter\"");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.Progress.UserProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("LastCompletedPublishDate")
                        .HasColumnType("date");

                    b.Property<long>("LifetimeXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserProgress", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserProgress_NonNegative", "\"LifetimeXp\" >= 0 AND \"CurrentStreak\" >= 0 AND \"LongestStreak\" >= \"CurrentStreak\"");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.Progress.XpLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique()
                        .HasDatabaseName("UX_XpLedger_AttemptId");

                    b.HasIndex("OccurredAt", "Amount")
                        .HasDatabaseName("IX_XpLedger_OccurredAt_Amount");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("IX_XpLedger_UserId_OccurredAt");

                    b.ToTable("XpLedger", null, t =>
                        {
                            t.HasCheckConstraint("CK_XpLedger_ExactAmount", "\"Amount\" IN (10, 15)");
                        });
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.Challenge", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlisRevision", null)
                        .WithOne("Challenge")
                        .HasForeignKey("Majlis.Domain.DailyMajlis.Challenge", "RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.ChallengeOption", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.Challenge", null)
                        .WithMany("Options")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.ChallengeOptionTranslation", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.ChallengeOption", null)
                        .WithMany("Translations")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlis", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlisRevision", "PublishedRevision")
                        .WithMany()
                        .HasForeignKey("PublishedRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlisRevision", "ScheduledRevision")
                        .WithMany()
                        .HasForeignKey("ScheduledRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PublishedRevision");

                    b.Navigation("ScheduledRevision");
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlisPublication", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlis", null)
                        .WithOne("Publication")
                        .HasForeignKey("Majlis.Domain.DailyMajlis.DailyMajlisPublication", "DailyMajlisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlisRevision", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlis", null)
                        .WithMany()
                        .HasForeignKey("DailyMajlisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlisRevision", null)
                        .WithMany()
                        .HasForeignKey("SupersedesRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlisTranslation", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlisRevision", null)
                        .WithMany("Translations")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.RevisionDialect", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlisRevision", null)
                        .WithMany("Dialects")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.RevisionRegion", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlisRevision", null)
                        .WithMany("Regions")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.Identity.AccountDeletionRequest", b =>
                {
                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithMany("DeletionRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserConsent", b =>
                {
                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserIdentity", b =>
                {
                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserPreferences", b =>
                {
                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithOne("Preferences")
                        .HasForeignKey("Majlis.Domain.Identity.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserProfile", b =>
                {
                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithOne("Profile")
                        .HasForeignKey("Majlis.Domain.Identity.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserRoleAssignment", b =>
                {
                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Majlis.Domain.Progress.IdempotencyRecord", b =>
                {
                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IdempotencyRecords_Users_UserId");
                });

            modelBuilder.Entity("Majlis.Domain.Progress.UserAttempt", b =>
                {
                    b.HasOne("Majlis.Domain.DailyMajlis.DailyMajlis", null)
                        .WithMany()
                        .HasForeignKey("DailyMajlisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserAttempts_DailyMajlis_DailyMajlisId");

                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAttempts_Users_UserId");

                    b.HasOne("Majlis.Domain.DailyMajlis.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId", "ContentRevisionId")
                        .HasPrincipalKey("Id", "RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserAttempts_Challenges_ChallengeId_ContentRevisionId");

                    b.HasOne("Majlis.Domain.DailyMajlis.ChallengeOption", null)
                        .WithMany()
                        .HasForeignKey("SelectedOptionId", "ChallengeId")
                        .HasPrincipalKey("Id", "ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserAttempts_ChallengeOptions_SelectedOptionId_ChallengeId");
                });

            modelBuilder.Entity("Majlis.Domain.Progress.UserProgress", b =>
                {
                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Majlis.Domain.Progress.UserProgress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserProgress_Users_UserId");
                });

            modelBuilder.Entity("Majlis.Domain.Progress.XpLedgerEntry", b =>
                {
                    b.HasOne("Majlis.Domain.Progress.UserAttempt", null)
                        .WithOne()
                        .HasForeignKey("Majlis.Domain.Progress.XpLedgerEntry", "AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_XpLedger_UserAttempts_AttemptId");

                    b.HasOne("Majlis.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_XpLedger_Users_UserId");
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.Challenge", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.ChallengeOption", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlis", b =>
                {
                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Majlis.Domain.DailyMajlis.DailyMajlisRevision", b =>
                {
                    b.Navigation("Challenge");

                    b.Navigation("Dialects");

                    b.Navigation("Regions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Majlis.Domain.Identity.UserAccount", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("DeletionRequests");

                    b.Navigation("Identities");

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
